//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActifWebClientAspNet.ActifServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActifServiceReference.IActifService")]
    public interface IActifService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActifService/getActif", ReplyAction="http://tempuri.org/IActifService/getActifResponse")]
        string getActif(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActifService/getActif", ReplyAction="http://tempuri.org/IActifService/getActifResponse")]
        System.Threading.Tasks.Task<string> getActifAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActifServiceChannel : ActifWebClientAspNet.ActifServiceReference.IActifService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActifServiceClient : System.ServiceModel.ClientBase<ActifWebClientAspNet.ActifServiceReference.IActifService>, ActifWebClientAspNet.ActifServiceReference.IActifService {
        
        public ActifServiceClient() {
        }
        
        public ActifServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActifServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActifServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActifServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getActif(string name) {
            return base.Channel.getActif(name);
        }
        
        public System.Threading.Tasks.Task<string> getActifAsync(string name) {
            return base.Channel.getActifAsync(name);
        }
    }
}
