//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Historique.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrary.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Historique.ServiceReference.DataExchangeRate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Historique.ServiceReference.DataInterestRate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Historique.ServiceReference.DataActif))]
    public partial class Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet DsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Historique.ServiceReference.Data.TypeData TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Columns {
            get {
                return this.ColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnsField, value) != true)) {
                    this.ColumnsField = value;
                    this.RaisePropertyChanged("Columns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Debut {
            get {
                return this.DebutField;
            }
            set {
                if ((this.DebutField.Equals(value) != true)) {
                    this.DebutField = value;
                    this.RaisePropertyChanged("Debut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet Ds {
            get {
                return this.DsField;
            }
            set {
                if ((object.ReferenceEquals(this.DsField, value) != true)) {
                    this.DsField = value;
                    this.RaisePropertyChanged("Ds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fin {
            get {
                return this.FinField;
            }
            set {
                if ((this.FinField.Equals(value) != true)) {
                    this.FinField = value;
                    this.RaisePropertyChanged("Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Historique.ServiceReference.Data.TypeData Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Data.HistoricalColumn", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrary.Data")]
        public enum HistoricalColumn : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Open = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            High = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Low = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Close = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Volume = 4,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Data.TypeData", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrary.Data")]
        public enum TypeData : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            HistoricalData = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Currency = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            InterestRate = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RealTime = 3,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Data.Currency", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrary.Data")]
        public enum Currency : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ADF = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ADP = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AED = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AFA = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AFN = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AFR = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ALL = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AMD = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ANG = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AOA = 9,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AON = 10,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ARS = 11,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ATS = 12,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AUD = 13,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AWF = 14,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AWG = 15,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AZM = 16,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AZN = 17,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BAM = 18,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BBD = 19,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BDT = 20,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BEF = 21,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BGL = 22,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BGN = 23,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BHD = 24,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BIF = 25,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BMD = 26,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BND = 27,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BOB = 28,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BRL = 29,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BSD = 30,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BTN = 31,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BWP = 32,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BYR = 33,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BZD = 34,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CAD = 35,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CDF = 36,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CHF = 37,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CLP = 38,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CNY = 39,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            COP = 40,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CRS = 41,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CUC = 42,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CUP = 43,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CVE = 44,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CYP = 45,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CZK = 46,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DEM = 47,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DIF = 48,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DKK = 49,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DOP = 50,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DZF = 51,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ECS = 52,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            EEK = 53,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            EGP = 54,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ERN = 55,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ESP = 56,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ETD = 57,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            EUR = 58,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            FIM = 59,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            FJD = 60,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            FKP = 61,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GBP = 62,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GEL = 63,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GGP = 64,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GHC = 65,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GHS = 66,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GIP = 67,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GMP = 68,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GNF = 69,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GRD = 70,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GTQ = 71,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GYD = 72,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            HKD = 73,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            HNL = 74,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            HRK = 75,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            HTG = 76,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            HUF = 77,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            IDR = 78,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            IEP = 79,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ILS = 80,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            IMP = 81,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INR = 82,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            IQD = 83,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            IRR = 84,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ISK = 85,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ITL = 86,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            JEP = 87,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            JMP = 88,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            JOD = 89,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            JPY = 90,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KES = 91,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KGS = 92,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KHR = 93,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KMF = 94,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KPW = 95,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KRW = 96,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KWD = 97,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KYD = 98,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KZT = 99,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LAK = 100,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LBP = 101,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LKR = 102,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LRD = 103,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LSL = 104,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LTL = 105,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LUF = 106,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LVL = 107,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LYD = 108,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MAD = 109,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MDL = 110,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MGA = 111,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MGF = 112,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MKD = 113,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MMK = 114,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MNT = 115,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MOP = 116,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MRO = 117,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MTL = 118,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MUR = 119,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MVR = 120,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MWK = 121,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MXN = 122,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MYR = 123,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MZM = 124,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MZN = 125,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NAD = 126,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NGN = 127,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NIO = 128,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NLG = 129,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NOK = 130,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NPR = 131,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NTD = 132,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NZD = 133,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OMR = 134,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PAB = 135,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PEN = 136,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PGK = 137,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PHP = 138,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PKR = 139,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PLN = 140,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PSL = 141,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PTE = 142,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PYG = 143,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            QAR = 144,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ROL = 145,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RON = 146,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RSD = 147,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RUB = 148,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RWF = 149,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SAR = 150,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SBD = 151,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SCR = 152,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SDD = 153,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SDG = 154,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SDP = 155,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SEK = 156,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SGD = 157,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SHP = 158,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SIT = 159,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SKK = 160,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SLL = 161,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SOS = 162,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SPL = 163,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SRD = 164,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SRG = 165,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            STD = 166,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SVC = 167,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SVP = 168,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SZL = 169,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            THB = 170,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TJS = 171,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TMM = 172,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TND = 173,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TOP = 174,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TRL = 175,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TRY = 176,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TTD = 177,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TYD = 178,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TWD = 179,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TZS = 180,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UAH = 181,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UGX = 182,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USD = 183,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UYP = 184,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UYU = 185,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UZS = 186,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            VAL = 187,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            VEB = 188,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            VEF = 189,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            VND = 190,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            VUV = 191,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            WST = 192,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            XAF = 193,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            XAG = 194,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            XAU = 195,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            XCD = 196,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            XDR = 197,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            XEU = 198,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            XOF = 199,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            XPD = 200,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            XPF = 201,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            XPT = 202,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            YER = 203,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            YUN = 204,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ZAR = 205,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ZMK = 206,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ZWD = 207,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Data.Frequency", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrary.Data")]
        public enum Frequency : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Daily = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Monthly = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Yearly = 2,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Data.InterestRate", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrary.Data")]
        public enum InterestRate : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            EURIBOR = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USDEURIBOR = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            EONIA = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            EUREPO = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            EONIASWAP = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataExchangeRate", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrary.Data")]
    [System.SerializableAttribute()]
    public partial class DataExchangeRate : Historique.ServiceReference.Data {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataInterestRate", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrary.Data")]
    [System.SerializableAttribute()]
    public partial class DataInterestRate : Historique.ServiceReference.Data {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataActif", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrary.Data")]
    [System.SerializableAttribute()]
    public partial class DataActif : Historique.ServiceReference.Data {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IActifService")]
    public interface IActifService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActifService/getActifHistorique", ReplyAction="http://tempuri.org/IActifService/getActifHistoriqueResponse")]
        Historique.ServiceReference.DataActif getActifHistorique(System.Collections.Generic.List<string> symbol, System.Collections.Generic.List<Historique.ServiceReference.Data.HistoricalColumn> columns, System.DateTime debut, System.DateTime fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActifService/getActifHistorique", ReplyAction="http://tempuri.org/IActifService/getActifHistoriqueResponse")]
        System.Threading.Tasks.Task<Historique.ServiceReference.DataActif> getActifHistoriqueAsync(System.Collections.Generic.List<string> symbol, System.Collections.Generic.List<Historique.ServiceReference.Data.HistoricalColumn> columns, System.DateTime debut, System.DateTime fin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActifServiceChannel : Historique.ServiceReference.IActifService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActifServiceClient : System.ServiceModel.ClientBase<Historique.ServiceReference.IActifService>, Historique.ServiceReference.IActifService {
        
        public ActifServiceClient() {
        }
        
        public ActifServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActifServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActifServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActifServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Historique.ServiceReference.DataActif getActifHistorique(System.Collections.Generic.List<string> symbol, System.Collections.Generic.List<Historique.ServiceReference.Data.HistoricalColumn> columns, System.DateTime debut, System.DateTime fin) {
            return base.Channel.getActifHistorique(symbol, columns, debut, fin);
        }
        
        public System.Threading.Tasks.Task<Historique.ServiceReference.DataActif> getActifHistoriqueAsync(System.Collections.Generic.List<string> symbol, System.Collections.Generic.List<Historique.ServiceReference.Data.HistoricalColumn> columns, System.DateTime debut, System.DateTime fin) {
            return base.Channel.getActifHistoriqueAsync(symbol, columns, debut, fin);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IExchangeRateService")]
    public interface IExchangeRateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeRateService/getExchangeRate", ReplyAction="http://tempuri.org/IExchangeRateService/getExchangeRateResponse")]
        Historique.ServiceReference.DataExchangeRate getExchangeRate(Historique.ServiceReference.Data.Currency symbol, System.Collections.Generic.List<Historique.ServiceReference.Data.Currency> columns, System.DateTime debut, System.DateTime fin, Historique.ServiceReference.Data.Frequency freq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeRateService/getExchangeRate", ReplyAction="http://tempuri.org/IExchangeRateService/getExchangeRateResponse")]
        System.Threading.Tasks.Task<Historique.ServiceReference.DataExchangeRate> getExchangeRateAsync(Historique.ServiceReference.Data.Currency symbol, System.Collections.Generic.List<Historique.ServiceReference.Data.Currency> columns, System.DateTime debut, System.DateTime fin, Historique.ServiceReference.Data.Frequency freq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExchangeRateServiceChannel : Historique.ServiceReference.IExchangeRateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExchangeRateServiceClient : System.ServiceModel.ClientBase<Historique.ServiceReference.IExchangeRateService>, Historique.ServiceReference.IExchangeRateService {
        
        public ExchangeRateServiceClient() {
        }
        
        public ExchangeRateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExchangeRateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeRateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeRateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Historique.ServiceReference.DataExchangeRate getExchangeRate(Historique.ServiceReference.Data.Currency symbol, System.Collections.Generic.List<Historique.ServiceReference.Data.Currency> columns, System.DateTime debut, System.DateTime fin, Historique.ServiceReference.Data.Frequency freq) {
            return base.Channel.getExchangeRate(symbol, columns, debut, fin, freq);
        }
        
        public System.Threading.Tasks.Task<Historique.ServiceReference.DataExchangeRate> getExchangeRateAsync(Historique.ServiceReference.Data.Currency symbol, System.Collections.Generic.List<Historique.ServiceReference.Data.Currency> columns, System.DateTime debut, System.DateTime fin, Historique.ServiceReference.Data.Frequency freq) {
            return base.Channel.getExchangeRateAsync(symbol, columns, debut, fin, freq);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IInterestRateService")]
    public interface IInterestRateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateService/getInterestRate", ReplyAction="http://tempuri.org/IInterestRateService/getInterestRateResponse")]
        Historique.ServiceReference.DataInterestRate getInterestRate(Historique.ServiceReference.Data.InterestRate symbol, System.DateTime debut, System.DateTime fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateService/getInterestRate", ReplyAction="http://tempuri.org/IInterestRateService/getInterestRateResponse")]
        System.Threading.Tasks.Task<Historique.ServiceReference.DataInterestRate> getInterestRateAsync(Historique.ServiceReference.Data.InterestRate symbol, System.DateTime debut, System.DateTime fin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterestRateServiceChannel : Historique.ServiceReference.IInterestRateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterestRateServiceClient : System.ServiceModel.ClientBase<Historique.ServiceReference.IInterestRateService>, Historique.ServiceReference.IInterestRateService {
        
        public InterestRateServiceClient() {
        }
        
        public InterestRateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterestRateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterestRateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterestRateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Historique.ServiceReference.DataInterestRate getInterestRate(Historique.ServiceReference.Data.InterestRate symbol, System.DateTime debut, System.DateTime fin) {
            return base.Channel.getInterestRate(symbol, debut, fin);
        }
        
        public System.Threading.Tasks.Task<Historique.ServiceReference.DataInterestRate> getInterestRateAsync(Historique.ServiceReference.Data.InterestRate symbol, System.DateTime debut, System.DateTime fin) {
            return base.Channel.getInterestRateAsync(symbol, debut, fin);
        }
    }
}
